version: '3.9'

services:
  appd:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app/
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    container_name: pdb
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432